name: Build & Deploy Next.js to S3

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ap-southeast-1
  ROLE_ARN: arn:aws:iam::192933325418:role/GithubActionsDeploy
  S3_BUCKET: leerically-com-site
  S3_PREFIX: web
  CF_DISTRIBUTION_ID: E9CHNVBXBNU4W
  JEKYLL_ENV: production

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: deploy
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.19.0'

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js app
        run: npm run build

      - name: Clone Leerically-data repo
        uses: actions/checkout@v4
        with:
          repository: leeyanleryan/Leerically-data
          token: ${{ secrets.DATA_REPO_TOKEN }}
          path: leerically-data

      - name: Copy data folders to out/data
        run: |
          mkdir -p ./out/data
          cp -r ./leerically-data/songs ./out/data/
          cp -r ./leerically-data/word-banks ./out/data/

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Sync out to S3
        run: |
          aws s3 sync ./out s3://${{ env.S3_BUCKET }}/${{ env.S3_PREFIX }} --delete --only-show-errors
          
      - name: Invalidate CloudFront
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ env.CF_DISTRIBUTION_ID }} --paths "/*"
